/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlbhtt;

/**
 *
 * @author DMX
 */
public class ManHinh_NV_ThongKeDoanhThu extends javax.swing.JPanel {

    /**
     * Creates new form quanly
     */
    public ManHinh_NV_ThongKeDoanhThu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DS_SanPham = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Talbe_SanPham = new javax.swing.JTable();
        information = new javax.swing.JPanel();
        lb_phanLoai = new javax.swing.JLabel();
        lb_kichThuoc = new javax.swing.JLabel();
        lb_mauSac = new javax.swing.JLabel();
        lb_tuNgay = new javax.swing.JLabel();
        txt_tuNgay = new javax.swing.JTextField();
        panel_hinhanh = new javax.swing.JPanel();
        lb_tongSPBan = new javax.swing.JLabel();
        txt_tongSPBan = new javax.swing.JTextField();
        cb_phanLoai = new javax.swing.JComboBox<>();
        cb_mauSac = new javax.swing.JComboBox<>();
        cb_kichThuoc = new javax.swing.JComboBox<>();
        panel_hinhanh1 = new javax.swing.JPanel();
        lb_tongSPBan1 = new javax.swing.JLabel();
        txt_tongDoanhThu = new javax.swing.JTextField();
        lb_denNgay = new javax.swing.JLabel();
        txt_denNgay = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        panel_button = new javax.swing.JPanel();
        btn_xuatThongKe = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        Talbe_SanPham.setBackground(new java.awt.Color(255, 255, 255));
        Talbe_SanPham.setForeground(new java.awt.Color(0, 0, 0));
        Talbe_SanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SP0001", "Áo thun", "Áo", "250000", "275000", "L", "Trắng", "Cotton", "CT TNHH Hades", "10", "500000", "12"},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Phân loại", "Giá bán ", "Giá nhập", "Kích cỡ", "Màu sắc", "Chất liệu", "Nhà cung cấp", "Số lượng tồn", "Số lượng đã bán", "Tỷ lệ doanh thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Talbe_SanPham.setShowGrid(true);
        jScrollPane1.setViewportView(Talbe_SanPham);
        if (Talbe_SanPham.getColumnModel().getColumnCount() > 0) {
            Talbe_SanPham.getColumnModel().getColumn(11).setMinWidth(100);
        }

        javax.swing.GroupLayout DS_SanPhamLayout = new javax.swing.GroupLayout(DS_SanPham);
        DS_SanPham.setLayout(DS_SanPhamLayout);
        DS_SanPhamLayout.setHorizontalGroup(
            DS_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        DS_SanPhamLayout.setVerticalGroup(
            DS_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        information.setBackground(new java.awt.Color(199, 210, 213));
        information.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_phanLoai.setForeground(new java.awt.Color(0, 0, 0));
        lb_phanLoai.setText("Phân loại");

        lb_kichThuoc.setForeground(new java.awt.Color(0, 0, 0));
        lb_kichThuoc.setText("Kích thước");

        lb_mauSac.setForeground(new java.awt.Color(0, 0, 0));
        lb_mauSac.setText("Màu sắc");

        lb_tuNgay.setForeground(new java.awt.Color(0, 0, 0));
        lb_tuNgay.setText("Từ ngày:");

        txt_tuNgay.setBackground(new java.awt.Color(255, 255, 255));
        txt_tuNgay.setForeground(new java.awt.Color(0, 0, 0));
        txt_tuNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tuNgayActionPerformed(evt);
            }
        });

        panel_hinhanh.setBackground(new java.awt.Color(255, 255, 255));
        panel_hinhanh.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lb_tongSPBan.setForeground(new java.awt.Color(0, 0, 0));
        lb_tongSPBan.setText("Tổng sản phẩm bán được");

        txt_tongSPBan.setBackground(new java.awt.Color(255, 255, 255));
        txt_tongSPBan.setForeground(new java.awt.Color(0, 0, 0));
        txt_tongSPBan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tongSPBan.setText("2");
        txt_tongSPBan.setBorder(null);

        javax.swing.GroupLayout panel_hinhanhLayout = new javax.swing.GroupLayout(panel_hinhanh);
        panel_hinhanh.setLayout(panel_hinhanhLayout);
        panel_hinhanhLayout.setHorizontalGroup(
            panel_hinhanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hinhanhLayout.createSequentialGroup()
                .addGroup(panel_hinhanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_hinhanhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_tongSPBan))
                    .addGroup(panel_hinhanhLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txt_tongSPBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panel_hinhanhLayout.setVerticalGroup(
            panel_hinhanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hinhanhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tongSPBan)
                .addGap(26, 26, 26)
                .addComponent(txt_tongSPBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        cb_phanLoai.setBackground(new java.awt.Color(255, 255, 255));
        cb_phanLoai.setForeground(new java.awt.Color(0, 0, 0));
        cb_phanLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áo" }));

        cb_mauSac.setBackground(new java.awt.Color(255, 255, 255));
        cb_mauSac.setForeground(new java.awt.Color(0, 0, 0));
        cb_mauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng" }));

        cb_kichThuoc.setBackground(new java.awt.Color(255, 255, 255));
        cb_kichThuoc.setForeground(new java.awt.Color(0, 0, 0));
        cb_kichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L" }));

        panel_hinhanh1.setBackground(new java.awt.Color(255, 255, 255));
        panel_hinhanh1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lb_tongSPBan1.setForeground(new java.awt.Color(0, 0, 0));
        lb_tongSPBan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tongSPBan1.setText("Tổng doanh thu");

        txt_tongDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        txt_tongDoanhThu.setForeground(new java.awt.Color(0, 0, 0));
        txt_tongDoanhThu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tongDoanhThu.setText("1,375,000");
        txt_tongDoanhThu.setBorder(null);

        javax.swing.GroupLayout panel_hinhanh1Layout = new javax.swing.GroupLayout(panel_hinhanh1);
        panel_hinhanh1.setLayout(panel_hinhanh1Layout);
        panel_hinhanh1Layout.setHorizontalGroup(
            panel_hinhanh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hinhanh1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_tongSPBan1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_hinhanh1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_tongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panel_hinhanh1Layout.setVerticalGroup(
            panel_hinhanh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hinhanh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tongSPBan1)
                .addGap(29, 29, 29)
                .addComponent(txt_tongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_denNgay.setForeground(new java.awt.Color(0, 0, 0));
        lb_denNgay.setText("Đến ngày:");

        txt_denNgay.setBackground(new java.awt.Color(255, 255, 255));
        txt_denNgay.setForeground(new java.awt.Color(0, 0, 0));
        txt_denNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_denNgayActionPerformed(evt);
            }
        });

        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Tất cả");

        javax.swing.GroupLayout informationLayout = new javax.swing.GroupLayout(information);
        information.setLayout(informationLayout);
        informationLayout.setHorizontalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel_hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panel_hinhanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationLayout.createSequentialGroup()
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_kichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_phanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informationLayout.createSequentialGroup()
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_mauSac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_kichThuoc, 0, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_tuNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_denNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_denNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(informationLayout.createSequentialGroup()
                        .addComponent(lb_phanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)))
                .addContainerGap())
        );
        informationLayout.setVerticalGroup(
            informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lb_kichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informationLayout.createSequentialGroup()
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_kichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_tuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_mauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_denNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_denNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_phanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)))
                    .addGroup(informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panel_hinhanh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel_hinhanh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_phanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel_button.setBackground(new java.awt.Color(199, 210, 213));

        btn_xuatThongKe.setBackground(new java.awt.Color(199, 210, 213));
        btn_xuatThongKe.setForeground(new java.awt.Color(0, 0, 0));
        btn_xuatThongKe.setText("Xuất thống kê");
        btn_xuatThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_buttonLayout = new javax.swing.GroupLayout(panel_button);
        panel_button.setLayout(panel_buttonLayout);
        panel_buttonLayout.setHorizontalGroup(
            panel_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_xuatThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_buttonLayout.setVerticalGroup(
            panel_buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_buttonLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_xuatThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(DS_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DS_SanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_tuNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tuNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuNgayActionPerformed

    private void txt_denNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_denNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_denNgayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DS_SanPham;
    private javax.swing.JTable Talbe_SanPham;
    private javax.swing.JButton btn_xuatThongKe;
    private javax.swing.JComboBox<String> cb_kichThuoc;
    private javax.swing.JComboBox<String> cb_mauSac;
    private javax.swing.JComboBox<String> cb_phanLoai;
    private javax.swing.JPanel information;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_denNgay;
    private javax.swing.JLabel lb_kichThuoc;
    private javax.swing.JLabel lb_mauSac;
    private javax.swing.JLabel lb_phanLoai;
    private javax.swing.JLabel lb_tongSPBan;
    private javax.swing.JLabel lb_tongSPBan1;
    private javax.swing.JLabel lb_tuNgay;
    private javax.swing.JPanel panel_button;
    private javax.swing.JPanel panel_hinhanh;
    private javax.swing.JPanel panel_hinhanh1;
    private javax.swing.JTextField txt_denNgay;
    private javax.swing.JTextField txt_tongDoanhThu;
    private javax.swing.JTextField txt_tongSPBan;
    private javax.swing.JTextField txt_tuNgay;
    // End of variables declaration//GEN-END:variables
}
