/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlbhtt;

/**
 *
 * @author DMX
 */
public class ManHinh_NV_XemDSHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form quanly
     */
    public ManHinh_NV_XemDSHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DS_XemHD = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Talbe_HoaDon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jsc = new javax.swing.JScrollPane();
        Table_CTHD = new javax.swing.JTable();
        Information = new javax.swing.JPanel();
        txt_ngayDen = new javax.swing.JTextField();
        txt_ngayTu = new javax.swing.JTextField();
        lb_tuNgay = new javax.swing.JLabel();
        lb_denNgay = new javax.swing.JLabel();
        cb_tatCa = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        DS_XemHD.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        Talbe_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        Talbe_HoaDon.setForeground(new java.awt.Color(0, 0, 0));
        Talbe_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {"", null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Mã KH", "Tên KH", "Mã NV", "Tên NV", "Ngày lập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Talbe_HoaDon.setShowGrid(true);
        jScrollPane1.setViewportView(Talbe_HoaDon);
        if (Talbe_HoaDon.getColumnModel().getColumnCount() > 0) {
            Talbe_HoaDon.getColumnModel().getColumn(4).setHeaderValue("Tên NV");
            Talbe_HoaDon.getColumnModel().getColumn(5).setHeaderValue("Ngày lập");
            Talbe_HoaDon.getColumnModel().getColumn(6).setHeaderValue("Tổng tiền");
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết hóa đơn tương ứng"));

        Table_CTHD.setBackground(new java.awt.Color(255, 255, 255));
        Table_CTHD.setForeground(new java.awt.Color(0, 0, 0));
        Table_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {"", null, null, null}
            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_CTHD.setShowGrid(true);
        jsc.setViewportView(Table_CTHD);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jsc, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsc, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DS_XemHDLayout = new javax.swing.GroupLayout(DS_XemHD);
        DS_XemHD.setLayout(DS_XemHDLayout);
        DS_XemHDLayout.setHorizontalGroup(
            DS_XemHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DS_XemHDLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DS_XemHDLayout.setVerticalGroup(
            DS_XemHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Information.setBackground(new java.awt.Color(199, 210, 213));
        Information.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_ngayDen.setBackground(new java.awt.Color(255, 255, 255));
        txt_ngayDen.setForeground(new java.awt.Color(0, 0, 0));
        txt_ngayDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngayDenActionPerformed(evt);
            }
        });

        txt_ngayTu.setBackground(new java.awt.Color(255, 255, 255));
        txt_ngayTu.setForeground(new java.awt.Color(0, 0, 0));
        txt_ngayTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngayTuActionPerformed(evt);
            }
        });

        lb_tuNgay.setForeground(new java.awt.Color(0, 0, 0));
        lb_tuNgay.setText("Từ ngày:");

        lb_denNgay.setForeground(new java.awt.Color(0, 0, 0));
        lb_denNgay.setText("Đến ngày:");

        cb_tatCa.setForeground(new java.awt.Color(0, 0, 0));
        cb_tatCa.setText("Tất cả");
        cb_tatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InformationLayout = new javax.swing.GroupLayout(Information);
        Information.setLayout(InformationLayout);
        InformationLayout.setHorizontalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InformationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_tatCa)
                    .addGroup(InformationLayout.createSequentialGroup()
                        .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_tuNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_denNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ngayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ngayTu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        InformationLayout.setVerticalGroup(
            InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformationLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngayTu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(InformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ngayDen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_denNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cb_tatCa)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DS_XemHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DS_XemHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ngayDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngayDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngayDenActionPerformed

    private void txt_ngayTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngayTuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngayTuActionPerformed

    private void cb_tatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tatCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tatCaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DS_XemHD;
    private javax.swing.JPanel Information;
    private javax.swing.JTable Table_CTHD;
    private javax.swing.JTable Talbe_HoaDon;
    private javax.swing.JCheckBox cb_tatCa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jsc;
    private javax.swing.JLabel lb_denNgay;
    private javax.swing.JLabel lb_tuNgay;
    private javax.swing.JTextField txt_ngayDen;
    private javax.swing.JTextField txt_ngayTu;
    // End of variables declaration//GEN-END:variables
}
